### PR TITLE
Add default useragent to openurl

### PR DESCRIPTION
**Pull request by sottom**

### CODE REVIEW

**Comment by reubano** [comment]
Maybe you didn't see this in the chat...

If the riko UA isn't set then you should add a PR to set a default agent like in [psf/requests](https://github.com/psf/requests/blob/3e7d0a873f838e0001f7ac69b1987147128a7b5f/requests/utils.py#L798-L804)

e.g., 'riko/0.13.2'
 
So, by default it should use the above. But what you have is good, so there could be another option to select a random agent.

**Comment by sottom** [comment]
You're right, I missed that. Thank you for the correction! I've updated the code.

I removed the random agent because it's easy to re-add if you ever need it.

**Comment by sottom** [comment]
Done

**Comment by reubano** [comment]
> I removed the random agent because it's easy to re-add if you ever need it.

Can you add this back as a new PR? thanks!

**Pull request merged**
